### PR TITLE
Updated visuals. added 'disabled' state. 

### PR DESCRIPTION
**Pull request by rox163**
#minor#

### CODE REVIEW

**Comment by job13er** [comment]
I've got almost the identical change, along with a bunch of re-factoring of the source coming in a few minutes :(

**Comment by job13er** [comment]
I guess I'll just deal with the conflicts.

**Comment by rox163** [comment]
yay merges. 
I didn't refactor anything so maybe you merge my changes into yours? Mine would be less and mostly styling.

**Comment by job13er** [comment]
Yeah. It's probably easiest for me to look at this PR and apply anything I didn't already do into my PR. I'll do that. Thanks.

**Pull request closed without merging**
